---
- name: Install Apache and upload Web Page
  hosts: 
     - staging_servers
     - local_servers
  become: yes

  vars:
    source_file: ./WebSiteADV/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    yum:  name=httpd state=installed

  - name: Copy WebPage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0664
    notify: Restart Apache

  - name: Start Webservers and Enabled autostarting
    service: name=httpd state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted

