---
- name: Install default Apache Web Server
  hosts: all
  become: yes

  tasks:
  - name: Install Apache
    yum:  name=httpd state=installed

  - name: Start Apache and Enable it on boot
    service: name=httpd state=started enabled=yes

  - name: Uninstall Apache
    yum:  name=httpd state=removed
